name: Test Only

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
    
    - name: Lint with flake8
      run: |
        # Run flake8 with basic configuration
        flake8 . --count --exit-zero --max-line-length=127
    
    - name: Test with pytest (unit tests only)
      run: |
        # Try pytest first, fallback to our test runner if pytest is not available
        pytest tests/test_core_logic.py -v --tb=short || python test_runner.py
